### PR TITLE
Minor cleanup, comments, documentation

### PR DESCRIPTION
**Pull request by kamahen**

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Merged after a few patches.   Removed `-g -Werror`.   `-g` blows up the size of C++ code quite a bit and `-Werror` typically breaks installation on some compiler.    Just use locally!    Fixed the feature checking to use

      requires(prolog:c_cxx(_)).

As `prolog:c_cxx` tests boolean flags.   Here we want to check existence.     Also added `-f` to `$(RM)`.   Now builds nice, swift and clean (except for use of `tempnam` in one of the libcds tests).

**Comment by kamahen** [comment]
No need for `$(RM) -f` ... `$(RM)` is defined as `rm -f` (but it doesn't hurt to specify `-f` twice). https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

You removed my comment about why `LIBS=-L$(HDTLIB) -L$(CDSLIB) -lhdt -lcds` doesn't work -- the `.so` files take precedence; so instead the Makefile copies the `*.a` files and uses them. This took me a bit to figure out, so I'd like to restore that comment.

**Comment by JanWielemaker** [comment]
Ah, didn't know the `-f`.   Either with or without is fine with me.   The comment was wrong as we do not copy anything.  That was the case at some point, but now we just link them from the right location.   You could add a short comment that we explicitly link the static library.  I personally find all these comments typically more distracting than useful ...   Comments being often outdated is one reason :smile:

**Comment by kamahen** [comment]
Ahhh ... you made change f6a5f746949ab5a150cce4e47b45049cefd18e8a and I didn't notice. Your solution is better than mine and there's no need for my comment. (BTW, the ld(1) documentation says that `.so` are preferred over `.a` with no indication of how to change that ... my lack of understanding of Unix linkers is profound, and I intend to continue with not understanding them.)

**Comment by kamahen** [comment]
BTW, I'm not doing anything to update the page at https://www.swi-prolog.org/pack/list?p=hdt ... I assume that @jan will do this once the build is validated on all the relevant platforms.

**Comment by JanWielemaker** [comment]
I have pushed 0.5.4.   It should install with stable and devel and probably also older versions.   Finally, people can install a specific version.

**Comment by jan** [comment]
@kamahen I regret to inform you, that I can't work on that, Sir.

**Pull request closed without merging**
