### PR TITLE
Sync with hdt-cpp fixes + cleanup

### PR DESCRIPTION
**Pull request by kamahen**
I seem to have messed things up with hdt-cpp, by doing a rebase that removed one commit -- this has created a number of merge conflicts. The changes are in JanWielemaker/hdt-cpp, branch "develop-buffer", which should be merged into branch "develop".  

This is the same as https://github.com/rdfhdt/hdt-cpp/pull/275 , but that repo appears to not being maintained any more.

After hdt-cpp is fixed, this PR can be merged.

EDIT: https://github.com/rdfhdt/hdt-cpp/pull/275 has been replaced by https://github.com/rdfhdt/hdt-cpp/pull/283 ... once the latter has been merged into https://github.com/JanWielemaker/hdt-cpp/tree/develop, there remains one more commit to be done to this repo to sync to this fork of hdt-cpp.

### CODE REVIEW

**Comment by kamahen** [comment]
BTW, the comment with https://github.com/kamahen/hdt/commit/0b584c2da79a88eb75d0fd8d6f22bf81f6befab2 has "ack" instead of "pack" ... I didn't fix it with rebase -i because any time I use rebase, it seems to cause  bogus merge conflicts.

**Comment by kamahen** [comment]
The latest commit - using C++-17's shared_mutex - would benefit from someone reviewing the documentation for shared_mutex, scoped_lock, and shared_lock. I *think* that scoped_lock is exclusive (write) mutex and shared_lock is a read mutex; but the documentation I've found is a bit confusing, especially because there are older or variant versions of the interface (lock_guard, unique_lock, etc.) and I haven't been able to find an authoritative description of which are obsolete and which are best to use.

**Comment by kamahen** [comment]
Awaiting merge of https://github.com/JanWielemaker/hdt-cpp/tree/develop-buffer2 into https://github.com/JanWielemaker/hdt-cpp/tree/develop, plus a commit to sync.

(https://github.com/JanWielemaker/hdt/pull/12#issue-2381036237 has been edited)

**Comment by JanWielemaker** [comment]
Merged.  This removes all warnings from the interface.  Thanks.

**Comment by kamahen** [comment]
My apologies for mistakenly doing a "git commit -a", which picked up the
(wrong?) submodule hash. (I wish that github had a way of showing the merge
conflicts -- that would have made me realize my mistake and I could have
redone the PR)

**Pull request closed without merging**
